version: '3.4'

services:
  arcus.apis.bacon:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationInsights_InstrumentationKey=<key>
      - ARCUS_HTTP_PORT=999
    ports:
      - "789:999"
  arcus.apis.market:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationInsights_InstrumentationKey=<key>
      - ARCUS_HTTP_PORT=888
      - Bacon_API_Url=Arcus.API.Gateway:8080/market/bacon
      - Bacon_API_Key=<key>
    ports:
      - "787:888"
  arcus.apis.salads:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationInsights_InstrumentationKey=<key>
      - ARCUS_HTTP_PORT=777
    ports:
      - "788:777"
  arcus.api.gateway:
    environment:
      - config.service.endpoint=<endpoint>
      - config.service.auth=<key>
    ports:
      - "700:8080"