version: '3.4'

services:
  arcus.apis.bacon:
    container_name: Arcus.API.Bacon
    image: arcus.apis.bacon
    build:
      context: .
      dockerfile: Arcus.API.Bacon/Dockerfile
  arcus.apis.market:
    container_name: Arcus.API.Market
    image: arcus.apis.market
    build:
      context: .
      dockerfile: Arcus.API.Market/Dockerfile
  arcus.workers.orders:
    container_name: Arcus.Workers.Orders
    image: arcus.workers.orders
    build:
      context: .
      dockerfile: Arcus.Workers.Orders/Dockerfile