version: '3.4'

services:
  arcus.apis.bacon:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APPINSIGHTS_INSTRUMENTATIONKEY=<key>
      - ARCUS_HTTP_PORT=999
    ports:
      - "789:999"
  arcus.apis.market:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APPINSIGHTS_INSTRUMENTATIONKEY=<key>
      - ARCUS_HTTP_PORT=888
      - SERVICEBUS_CONNECTIONSTRING=<key>
      - Bacon_API_Url=Arcus.API.Bacon:999
    ports:
      - "787:888"
  arcus.workers.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APPINSIGHTS_INSTRUMENTATIONKEY=<key>
      - SERVICEBUS_CONNECTIONSTRING=<key>
      - Bacon_API_Url=Arcus.API.Bacon:999
